---Create User
CREATE USER HR_USER WITH ENCRYPTED PASSWORD 'HR@ABCCorp';

ALTER USER hr_user WITH CREATEDB;


--Create database HR_DB

CREATE DATABASE HR_DB
    WITH OWNER = HR_USER;
	
COMMENT ON DATABASE HR_DB
    IS 'HR Database for Tech ABC Corp';

\c hr_db;

--Create schema HR_SCHEMA

CREATE SCHEMA HR_SCHEMA
    AUTHORIZATION HR_USER;
	
-------------------------------


CREATE TABLE HR_SCHEMA.JOB
(
JOB_ID SERIAL PRIMARY KEY,
JOB_TITLE VARCHAR(100)
);
------------------------------

CREATE TABLE HR_SCHEMA.SALARY
(
SALARY_ID SERIAL PRIMARY KEY,
SALARY_AMT DECIMAL(12,2)
);
------------------------------

CREATE TABLE HR_SCHEMA.DEPARTMENT
(
DEPT_ID SERIAL PRIMARY KEY,
DEPT_NM VARCHAR(100)
);
-------------------------------
CREATE TABLE HR_SCHEMA.EDUCATION
(
EDUCATION_ID SERIAL PRIMARY KEY,
EDUCATION_LEVEL VARCHAR(100)
);
-------------------------------
CREATE TABLE HR_SCHEMA.ADDRESS
(
ADDRESS_ID SERIAL PRIMARY KEY,
ADDRESS_LINE1 VARCHAR(200),
CITY VARCHAR(100),
STATE VARCHAR(100)
);
-------------------------------
CREATE TABLE HR_SCHEMA.LOCATION
(
LOCATION_ID SERIAL PRIMARY KEY,
LOCATION_CODE VARCHAR(100),
ADDRESS_ID INT REFERENCES HR_SCHEMA.ADDRESS(ADDRESS_ID)
);
-------------------------------
CREATE TABLE HR_SCHEMA.EMPLOYEE
(
EMP_ID VARCHAR(10) PRIMARY KEY,
EMP_NM VARCHAR(100),
EMAIL VARCHAR(100),
HIRE_DT DATE,
EDUCATION_ID INT REFERENCES HR_SCHEMA.EDUCATION(EDUCATION_ID)
);

-------------------------------
CREATE TABLE HR_SCHEMA.EMPLOYMENT
(
EMPLOYMENT SERIAL PRIMARY KEY,
EMP_ID VARCHAR(10) REFERENCES HR_SCHEMA.EMPLOYEE(EMP_ID),
JOB_ID INT REFERENCES HR_SCHEMA.JOB(JOB_ID),
SALARY_ID INT REFERENCES HR_SCHEMA.SALARY(SALARY_ID),
DEPT_ID INT REFERENCES HR_SCHEMA.DEPARTMENT(DEPT_ID),
MANAGER_ID VARCHAR(10) REFERENCES HR_SCHEMA.EMPLOYEE(EMP_ID),
LOCATION_ID INT REFERENCES HR_SCHEMA.LOCATION(LOCATION_ID),
START_DT DATE,
END_DT DATE
);
